export default {
  login: "Orphee1",
  id: 55689599,
  node_id: "MDQ6VXNlcjU1Njg5NTk5",
  avatar_url: "https://avatars0.githubusercontent.com/u/55689599?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Orphee1",
  html_url: "https://github.com/Orphee1",
  followers_url: "https://api.github.com/users/Orphee1/followers",
  following_url: "https://api.github.com/users/Orphee1/following{/other_user}",
  gists_url: "https://api.github.com/users/Orphee1/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Orphee1/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Orphee1/subscriptions",
  organizations_url: "https://api.github.com/users/Orphee1/orgs",
  repos_url: "https://api.github.com/users/Orphee1/repos",
  events_url: "https://api.github.com/users/Orphee1/events{/privacy}",
  received_events_url: "https://api.github.com/users/Orphee1/received_events",
  type: "User",
  site_admin: false,
  name: "Hugo Lattard",
  company: null,
  blog: "hugo-lattard-webdev.netlify.app/",
  location: "Bordeaux",
  email: null,
  hireable: true,
  bio: "React, React Native & Node.js developer. ",
  twitter_username: "HugoLattard",
  public_repos: 25,
  public_gists: 0,
  followers: 2,
  following: 14,
  created_at: "2019-09-23T09:04:31Z",
  updated_at: "2020-12-25T23:11:37Z",
};
